dist: trusty
sudo: false
language: node_js
cache:
  directories:
  - node_modules
  yarn: true

node_js:
  - "8"

jobs:
  include:
    - stage: test
      script: yarn test && yarn coveralls

  stages:
    - Test
